Note:
    type: entity
    table: note
    indexes:
        iduser:
            columns:
                - idoffre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        note:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        commentaire:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        statut:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        idoffre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
