Offre:
    type: entity
    table: offre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        type:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        nbrepiece:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        datedebut:
            type: date
            nullable: true
            comment: ''
        datefin:
            type: date
            nullable: true
            comment: ''
        superficie:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        gouvernorat:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        delegation:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        localite:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        codepostal:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        photo1:
            type: blob
            nullable: false
            length: null
            fixed: false
            comment: ''
        photo2:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        photo3:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        publication:
            type: boolean
            nullable: true
            comment: ''
        notemoy:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        iduser:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
