User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        telephone:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        login:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        pwd:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
