security:
    access_denied_url: /erreur
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ANNONCEUR: ROLE_USER
        ROLE_CLIENT : ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me: true
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler: redirect.after.login
            remember_me:
                  key: %secret%    
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Client, role: ROLE_CLIENT }
        - { path: ^/Annonceur, role: ROLE_ANNONCEUR }
        - { path: ^/Admin, role: ROLE_ADMIN }        