services:
#    esprit_darkom.example:
#        class: Esprit\DarkomBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
   redirect.after.login:
     class: Esprit\UserBundle\Redirection\AfterLoginRedirection
     arguments: [@router]
  
     
     
